export const ARTICLES = [
  {
    id: 1,
    title: "The Future Is Now: AI-Powered Insulin Pumps That Think Like a Pancreas",
    titleTr: "Geleceğe Hoş Geldiniz: Pankreas Gibi Düşünen Yapay Zeka Destekli İnsülin Pompaları",
    image: "https://images.unsplash.com/photo-1530026405186-ed1f139313f8?w=600&q=80",
    category: "Technology",
    categoryTr: "Teknoloji",
    date: "March 2026",
    summary: "In 2026, closed-loop insulin delivery systems — often called 'artificial pancreas' devices — have reached a new level of sophistication. Powered by machine learning algorithms that analyze real-time glucose data, activity patterns, and even meal photos, these systems can predict blood sugar fluctuations up to 60 minutes in advance. Clinical trials published this year show a 40% reduction in hypoglycemic episodes compared to traditional pump therapy. The latest generation devices from Medtronic, Tandem, and several startups now integrate directly with smartwatches, eliminating the need for separate CGM receivers entirely. Patients report dramatically improved sleep quality as nighttime glucose management becomes fully automated. Endocrinologists are calling this the most significant advance in type 1 diabetes care since the discovery of insulin itself. The technology is also showing promise for type 2 patients on insulin therapy, with early studies suggesting better overall metabolic control. Regulatory approvals in the EU and US have accelerated, with several new systems expected to reach market by late 2026.",
    summaryTr: "2026'da kapalı döngülü insülin iletim sistemleri — çoğunlukla 'yapay pankreas' cihazları olarak adlandırılır — yeni bir sofistike seviyeye ulaştı. Gerçek zamanlı glikoz verilerini, aktivite kalıplarını ve hatta yemek fotoğraflarını analiz eden makine öğrenimi algoritmaları tarafından desteklenen bu sistemler, kan şekeri dalgalanmalarını 60 dakikaya kadar önceden tahmin edebiliyor. Bu yıl yayımlanan klinik araştırmalar, geleneksel pompa terapisine kıyasla hipoglisemi ataklarında %40 azalma gösteriyor. Medtronic, Tandem ve çeşitli girişimlerden en son nesil cihazlar artık doğrudan akıllı saatlerle entegre olarak ayrı CGM alıcılarına olan ihtiyacı ortadan kaldırıyor. Hastalar, gece glikoz yönetimi tamamen otomatik hale geldiğinde önemli ölçüde iyileşen uyku kalitesi bildiriyor.",
    source: "https://www.diabetes.org/diabetes-technology",
    sourceName: "American Diabetes Association"
  },
  {
    id: 2,
    title: "Breaking: New Once-a-Week Insulin Injection Approved — A Game Changer for Millions",
    titleTr: "Son Dakika: Haftada Bir İnsülin Enjeksiyonu Onaylandı — Milyonlar İçin Oyun Değiştirici",
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&q=80",
    category: "Treatment",
    categoryTr: "Tedavi",
    date: "February 2026",
    summary: "The FDA's approval of icodec, a once-weekly basal insulin analogue, marks a watershed moment in diabetes management. For the estimated 537 million people living with diabetes worldwide, the prospect of replacing daily injections with a single weekly dose represents a profound quality-of-life improvement. Phase 3 clinical trials demonstrated non-inferior glycemic control compared to daily insulin glargine, with a similar safety profile. Patient adherence in the trials was significantly higher — 94% vs 78% — suggesting the weekly format will translate to real-world benefits. The injection uses a modified insulin molecule with an extended fatty acid chain that binds to albumin in the bloodstream, creating a slow-release depot. Novo Nordisk, the manufacturer, expects the medication to be available in most major markets by mid-2026. Health economists estimate the therapy could reduce hospitalization costs related to hypoglycemia by hundreds of millions annually. Doctors are particularly excited about its potential for elderly patients who struggle with daily injection routines.",
    summaryTr: "FDA'nın haftada bir bazal insülin analoğu olan icodec'i onaylaması, diyabet yönetiminde bir dönüm noktası oluşturuyor. Dünya genelinde tahminen 537 milyon diyabet hastası için günlük enjeksiyonların tek bir haftalık doza dönüştürülmesi olasılığı, derin bir yaşam kalitesi iyileştirmesi anlamına geliyor. Faz 3 klinik araştırmaları, günlük insülin glarjin ile karşılaştırıldığında benzer bir güvenlik profiliyle düşük olmayan glisemik kontrol gösterdi. Araştırmalardaki hasta uyumu önemli ölçüde daha yüksekti — %94'e karşı %78 — bu da haftalık formatın gerçek dünya faydalarına dönüşeceğini gösteriyor.",
    source: "https://www.nejm.org/doi/full/10.1056/NEJMoa2309169",
    sourceName: "New England Journal of Medicine"
  },
  {
    id: 3,
    title: "The Gut-Glucose Connection: How Your Microbiome Is Secretly Running Your Blood Sugar",
    titleTr: "Bağırsak-Glikoz Bağlantısı: Mikrobiyomunuz Kan Şekerinizi Gizlice Nasıl Yönetiyor?",
    image: "https://images.unsplash.com/photo-1628771065518-0d82f1938462?w=600&q=80",
    category: "Research",
    categoryTr: "Araştırma",
    date: "January 2026",
    summary: "Groundbreaking research published in Nature Metabolism in early 2026 has revealed the most detailed picture yet of how gut bacteria influence glucose metabolism. Scientists at the Broad Institute identified 47 specific bacterial species whose abundance strongly correlates with post-meal glucose spikes. People with high levels of Akkermansia muciniphila and Faecalibacterium prausnitzii showed 28% lower glucose variability after identical meals compared to those with low levels. The research opens the door to personalized nutrition recommendations based on microbiome profiling — a field already gaining commercial traction through companies offering gut-testing kits. Perhaps most intriguingly, the study found that certain probiotic interventions could shift microbiome composition in just 8 weeks, producing measurable improvements in insulin sensitivity. Researchers caution that we are still in early days, but clinical trials of microbiome-targeted therapies for type 2 diabetes are now underway at 12 major research centers globally.",
    summaryTr: "2026 yılı başında Nature Metabolism'de yayımlanan çığır açıcı araştırma, bağırsak bakterilerinin glikoz metabolizmasını nasıl etkilediğinin şimdiye kadarki en ayrıntılı resmini ortaya koydu. Broad Enstitüsü'ndeki bilim insanları, bolluğu yemek sonrası glikoz artışlarıyla güçlü biçimde ilişkilendirilen 47 spesifik bakteri türünü tanımladı. Yüksek Akkermansia muciniphila ve Faecalibacterium prausnitzii düzeylerine sahip kişiler, düşük düzeylere sahip olanlara kıyasla aynı öğünlerden sonra %28 daha düşük glikoz değişkenliği gösterdi.",
    source: "https://www.nature.com/nm",
    sourceName: "Nature Metabolism"
  },
  {
    id: 4,
    title: "Non-Invasive Glucose Monitoring: The Smartwatch That Could Replace Your Finger Prick",
    titleTr: "İnvazif Olmayan Glikoz İzleme: Parmak Deliğini Ortadan Kaldırabilecek Akıllı Saat",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80",
    category: "Technology",
    categoryTr: "Teknoloji",
    date: "March 2026",
    summary: "After years of false starts, non-invasive glucose monitoring via consumer wearables appears to be finally approaching clinical viability. Samsung's Galaxy Watch 8 Pro, released in early 2026, includes a near-infrared spectroscopy sensor that can estimate blood glucose within a 15% margin of error for most users — not yet accurate enough for insulin dosing decisions, but useful for trend monitoring and alerts. Apple is widely expected to include similar technology in its fall 2026 lineup, following successful internal trials. Meanwhile, a startup called Biolinq has developed a microscopic patch that sits on the skin and measures interstitial fluid glucose without penetrating the skin barrier, boasting accuracy comparable to traditional CGM sensors. The implications for people with diabetes are profound: continuous, painless monitoring that seamlessly integrates into daily life. Regulatory bodies in the US, EU, and South Korea are currently reviewing submissions for these devices, with some approvals expected before year's end.",
    summaryTr: "Yıllarca süren başarısız girişimlerin ardından, tüketici giyilebilir cihazlar aracılığıyla invazif olmayan glikoz izleme nihayet klinik uygulanabilirliğe yaklaşıyor gibi görünüyor. 2026 yılı başında piyasaya sürülen Samsung Galaxy Watch 8 Pro, çoğu kullanıcı için %15 hata payı içinde kan glikozunu tahmin edebilen yakın kızılötesi spektroskopi sensörü içeriyor. Apple'ın da benzer teknolojisi 2026 sonbaharında piyasaya sürmesi bekleniyor. Bu gelişmelerin diyabet hastaları için sonuçları derin: günlük yaşama sorunsuz entegre olan sürekli ve ağrısız izleme.",
    source: "https://www.thelancet.com/journals/landig/home",
    sourceName: "The Lancet Digital Health"
  },
  {
    id: 5,
    title: "Sugar Tax 2.0: How Countries Are Redesigning Food Policy to Fight the Diabetes Epidemic",
    titleTr: "Şeker Vergisi 2.0: Ülkeler Diyabet Salgınıyla Mücadelede Gıda Politikasını Nasıl Yeniden Tasarlıyor?",
    image: "https://images.unsplash.com/photo-1554978991-29f4dc65b4c8?w=600&q=80",
    category: "Policy",
    categoryTr: "Politika",
    date: "February 2026",
    summary: "A decade after the UK introduced the world's first sugar-sweetened beverage tax, a new wave of comprehensive food policy reforms is sweeping the globe. In 2026, over 60 countries now have some form of sugar tax in place, but the newest approaches go significantly further. Mexico has introduced mandatory front-of-pack warning labels on ultra-processed foods and banned their sale in schools. Colombia's tiered sugar tax, which increases in steps based on sugar content, has already shown a 22% reduction in sugary drink consumption in its first year. Australia is piloting a 'health star' rating system linked to tax incentives for manufacturers. Perhaps most controversially, France is experimenting with a 'diabetes prevention fund' — extra taxes on high-sugar products directed specifically toward diabetes research and prevention programs. Early data suggests these structural interventions may be more effective than individual-level health campaigns, particularly in lower-income populations disproportionately affected by type 2 diabetes.",
    summaryTr: "İngiltere'nin dünyada ilk şekerli içecek vergisini uygulamaya koymasından on yıl sonra, kapsamlı gıda politikası reformlarının yeni bir dalgası tüm dünyayı etkisi altına alıyor. 2026'da 60'tan fazla ülkede artık bir tür şeker vergisi mevcut, ancak en yeni yaklaşımlar çok daha ileri gidiyor. Meksika, ultra işlenmiş gıdalarda zorunlu ön etiket uyarıları getirdi ve bunların okullarda satışını yasakladı. Kolombiya'nın şeker içeriğine göre kademeli artan vergi sistemi ilk yılında şekerli içecek tüketiminde %22 azalma sağladı.",
    source: "https://www.who.int/news-room/fact-sheets/detail/diabetes",
    sourceName: "World Health Organization"
  },
  {
    id: 6,
    title: "Reversing Type 2: The Low-Calorie Diet Protocol That's Putting Diabetes Into Remission",
    titleTr: "Tip 2'yi Tersine Çevirmek: Diyabeti Remisyona Sokan Düşük Kalorili Diyet Protokolü",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&q=80",
    category: "Nutrition",
    categoryTr: "Beslenme",
    date: "January 2026",
    summary: "The DiRECT trial and its successors have now accumulated five years of follow-up data, cementing the scientific consensus that type 2 diabetes remission through intensive dietary intervention is not just possible but achievable for a meaningful proportion of patients. The protocol — typically involving an 800-calorie liquid diet for 12 weeks followed by structured food reintroduction — achieves complete remission in approximately 35% of participants at the two-year mark. New 2026 research has refined the approach: personalized macronutrient targets based on genetic profiling, microbiome composition, and individual insulin resistance patterns show remission rates approaching 50% in select populations. NHS England has now scaled the program nationwide, with over 200,000 patients enrolled. Several insurance providers in the US have begun covering the protocol after cost-effectiveness analyses showed savings of $12,000 per patient over five years. Researchers emphasize that remission is not a cure — careful monitoring is still essential — but for many patients, reducing or eliminating medication while achieving normal blood sugars represents a transformative outcome.",
    summaryTr: "DiRECT araştırması ve ardılları artık beş yıllık takip verisi biriktirdi ve yoğun diyet müdahalesi yoluyla tip 2 diyabet remisyonunun mümkün olmakla kalmayıp hastalar için anlamlı bir oran için gerçekleştirilebilir olduğuna dair bilimsel konsensüsü pekiştirdi. Protokol — genellikle 12 haftalık 800 kalorili sıvı diyeti ve ardından yapılandırılmış besin yeniden girişini içeriyor — iki yıllık izlemde katılımcıların yaklaşık %35'inde tam remisyon sağlıyor.",
    source: "https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(17)33102-1/fulltext",
    sourceName: "The Lancet"
  },
  {
    id: 7,
    title: "Mental Health & Diabetes: Breaking the Silence on 'Diabetes Distress'",
    titleTr: "Ruh Sağlığı ve Diyabet: 'Diyabet Sıkıntısı' Konusundaki Sessizliği Kırmak",
    image: "https://images.unsplash.com/photo-1499209974431-9dddcece7f88?w=600&q=80",
    category: "Wellbeing",
    categoryTr: "İyi Oluş",
    date: "March 2026",
    summary: "A landmark multi-country study published in JAMA Psychiatry has quantified what many patients have long reported anecdotally: people with diabetes are 2-3 times more likely to experience depression and anxiety than the general population. But the more nuanced finding is the concept of 'diabetes distress' — a condition distinct from clinical depression characterized by emotional burnout specifically related to the relentless demands of diabetes self-management. An estimated 45% of people with type 1 diabetes and 35% with type 2 experience significant diabetes distress at any given time. The good news: targeted psychological interventions, particularly acceptance and commitment therapy (ACT) and problem-solving therapy, show strong efficacy. In 2026, several diabetes centers have begun embedding clinical psychologists into their multidisciplinary teams as standard practice. Digital mental health tools specifically designed for diabetes patients are also gaining traction, with apps providing CBT modules, peer support communities, and burnout monitoring achieving meaningful reductions in distress scores in randomized trials.",
    summaryTr: "JAMA Psychiatry'de yayımlanan çok ülkeli önemli bir araştırma, birçok hastanın uzun süredir anekdot olarak bildirdiği şeyi sayısal hale getirdi: diyabeti olan kişilerin genel nüfusa kıyasla depresyon ve kaygı yaşama olasılığı 2-3 kat daha yüksek. Daha nüanslı bulgu ise 'diyabet sıkıntısı' kavramı — diyabet öz-yönetiminin amansız talepleriyle ilgili duygusal tükenmişlikle karakterize edilen, klinik depresyondan farklı bir durum. Tip 1 diyabetli kişilerin tahminen %45'i ve tip 2'li kişilerin %35'i herhangi bir zamanda önemli diyabet sıkıntısı yaşıyor.",
    source: "https://jamanetwork.com/journals/jamapsychiatry",
    sourceName: "JAMA Psychiatry"
  },
  {
    id: 8,
    title: "Stem Cell Breakthrough: Lab-Grown Beta Cells Offer Hope for Type 1 Cure",
    titleTr: "Kök Hücre Atılımı: Laboratuvarda Üretilen Beta Hücreler Tip 1 Diyabet Tedavisinde Umut Işığı",
    image: "https://images.unsplash.com/photo-1576086213369-97a306d36557?w=600&q=80",
    category: "Research",
    categoryTr: "Araştırma",
    date: "February 2026",
    summary: "Vertex Pharmaceuticals has announced two-year follow-up data from its VX-880 stem cell therapy trial that has sent shockwaves through the diabetes research community. Of the 12 patients who received the highest dose of lab-grown pancreatic beta cells, 9 achieved complete insulin independence at the 24-month mark — meaning they no longer need to inject insulin at all. The therapy involves infusing a patient with hundreds of millions of stem cell-derived beta cells that engraft in the liver and begin producing insulin in response to glucose signals. The remaining challenge is immunosuppression: patients currently need anti-rejection drugs, limiting candidacy to those with the most severe type 1 disease. However, a parallel program using encapsulation technology — essentially hiding the transplanted cells from the immune system in a biocompatible shell — has shown promising early results that could eventually eliminate the need for immunosuppression entirely. The diabetes research community is cautiously optimistic, with many experts suggesting a functional cure for type 1 diabetes could be within reach within the decade.",
    summaryTr: "Vertex Pharmaceuticals, diyabet araştırma topluluğunda sarsıcı dalgalar yaratan VX-880 kök hücre terapisi denemesinden iki yıllık takip verisi açıkladı. Laboratuvarda üretilmiş pankreas beta hücrelerinin en yüksek dozunu alan 12 hastanın 9'u, 24 aylık noktada tam insülin bağımsızlığı sağladı — yani artık insülin enjekte etmeleri gerekmiyor. Araştırma topluluğu, tip 1 diyabet için işlevsel bir tedavinin bu on yıl içinde erişilebilir olabileceğini düşünüyor.",
    source: "https://www.cell.com/cell-stem-cell/home",
    sourceName: "Cell Stem Cell"
  },
  {
    id: 9,
    title: "Ramadan & Diabetes: New Clinical Guidelines Make Fasting Safer Than Ever",
    titleTr: "Ramazan ve Diyabet: Yeni Klinik Kılavuzlar Orucu Her Zamankinden Daha Güvenli Yapıyor",
    image: "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=600&q=80",
    category: "Lifestyle",
    categoryTr: "Yaşam Tarzı",
    date: "January 2026",
    summary: "Updated guidelines released by the International Diabetes Federation in January 2026 represent the most comprehensive framework yet for managing diabetes during Ramadan fasting. With approximately 150 million Muslims with diabetes worldwide, the clinical and cultural importance of these guidelines cannot be overstated. The new recommendations stratify patients into risk categories and provide medication-specific dosing adjustments for Ramadan conditions. Key advances include clear protocols for SGLT-2 inhibitors — which carry DKA risk during fasting — and updated guidance on insulin dose reduction strategies. CGM use is strongly recommended for all fasting patients, with specific glucose alert thresholds defined for Suhoor (pre-dawn meal) and Iftar (breaking fast). The guidelines also address the unique challenge of dehydration in hot climates and its effect on glucose readings. Healthcare providers are encouraged to have a dedicated pre-Ramadan medical review with diabetes patients at least 6-8 weeks before fasting begins. The document acknowledges that fasting is a deeply important religious practice and aims to empower rather than discourage participation.",
    summaryTr: "Ocak 2026'da Uluslararası Diyabet Federasyonu tarafından yayımlanan güncellenmiş kılavuzlar, Ramazan orucu sırasında diyabet yönetimi için şimdiye kadarki en kapsamlı çerçeveyi temsil ediyor. Dünya genelinde yaklaşık 150 milyon diyabetli Müslüman ile bu kılavuzların klinik ve kültürel önemi abartılamaz. Yeni öneriler hastaları risk kategorilerine göre sınıflandırıyor ve Ramazan koşulları için ilaç bazlı doz ayarlamaları sağlıyor. CGM kullanımı, oruç tutan tüm hastalar için güçlü biçimde öneriliyor.",
    source: "https://www.idf.org/our-activities/education/diabetes-and-ramadan.html",
    sourceName: "International Diabetes Federation"
  },
  {
    id: 10,
    title: "Exercise as Medicine: The Exact Workout Protocol to Lower Your HbA1c in 12 Weeks",
    titleTr: "İlaç Olarak Egzersiz: HbA1c'nizi 12 Haftada Düşürecek Kesin Antrenman Protokolü",
    image: "https://images.unsplash.com/photo-1538805060514-97d9cc17730c?w=600&q=80",
    category: "Lifestyle",
    categoryTr: "Yaşam Tarzı",
    date: "March 2026",
    summary: "A major meta-analysis combining data from 87 randomized controlled trials and over 12,000 participants has produced the clearest picture yet of which exercise modalities are most effective for blood glucose management. The headline finding: a combination of resistance training and high-intensity interval training (HIIT) produces HbA1c reductions of 1.2-1.5% — comparable to adding a second oral medication — when performed consistently for 12 weeks. The optimal protocol identified was three weekly sessions alternating between 20-minute HIIT (4 cycles of 4 minutes hard, 3 minutes easy) and 30-minute resistance training targeting major muscle groups. Timing also matters: exercise performed 30-45 minutes after meals showed significantly better glucose disposal than fasted exercise. A secondary analysis found that even low-intensity walking (7,500+ steps daily) produced a 0.4% HbA1c reduction in sedentary type 2 patients. The researchers note that exercise works through multiple mechanisms — improving insulin sensitivity, increasing muscle glucose uptake, and reducing visceral fat — making it uniquely powerful compared to single-mechanism drugs.",
    summaryTr: "87 randomize kontrollü araştırmanın ve 12.000'den fazla katılımcının verilerini birleştiren kapsamlı bir meta-analiz, hangi egzersiz modalitelerinin kan glikoz yönetimi için en etkili olduğuna dair şimdiye kadarki en net tabloyu ortaya çıkardı. Başlıca bulgu: direnç antrenmanı ve yüksek yoğunluklu interval antrenmanının (HIIT) kombinasyonu, 12 hafta boyunca tutarlı biçimde uygulandığında %1,2-1,5 HbA1c düşüşü sağlıyor — bu, ikinci bir oral ilaç eklemeyle karşılaştırılabilir bir etki.",
    source: "https://diabetesjournals.org/care",
    sourceName: "Diabetes Care Journal"
  },
];
